# Generated by Django 3.2.2 on 2021-05-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
